### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by mchaver** [plow-technologies/plowtech-blog#1]
@KevinCotrone 
@smurphy8 

Take a look at my first post (one of a series on FFI, many more posts to come on Haskell).

http://blog.plowtech.net/posts/ffi-tutorial-part-1.html
- add email option to yaml and display on author's email
- text display is wider than the screen and i think the indentation should move more to the left, feels too far right
- tag is set to Javascript
- I like the boxes around code and inline code that markdown provides
- I think h3 font-weight bold looks nicer

**Comment by cotrone** [comment]
The sidebar behaves a little better now and I switched the titles to h2 (f0e960bca7f29ea736472eef6706c0de91833bdb).

Still need to add email and tags.

More suggestions! These were good. Thanks

**Comment by mchaver** [comment]
What do you think of wikipedia style references (footnotes)? I like be able to see all the referenced sources at the bottom.
https://en.wikipedia.org/wiki/Haskell_%28programming_language%29

Can define the references in the yaml file for each post (each reference should have a title, short blurb, if book/journal page number, link if website). Can have a numbered link in the post and/or <a href></a>.

**Comment by smurphy8** [comment]
That would be awesome!

**Comment by smurphy8** [comment]
well if this didn't get done it aint getting done now lol
