### ISSUE TITLE
Store code examples publicly

### ISSUE THREAD

**Issue by mchaver** [plow-technologies/plowtech-blog#2]
@smurphy8 
@KevinCotrone 

Not sure if we want plowtech-blog to be public or not, but I need a place to put example code so anyone that reads it can have easy access. Could be here (if you want plowtech-blog to be public) or another git repository

**Comment by cotrone** [comment]
I'm not sure what the best idea is but the repository is going to stay public.

**Comment by mchaver** [comment]
Ok, maybe just a top level dir (code) in plowtech-blog, if a post (thanks-kevin) has some code then put it in code/thanks-kevin
